export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 28,
    street: "123 Maple Street",
    city: "Springfield",
    state: "IL",
    zipCode: "62701",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    age: 34,
    street: "456 Oak Avenue",
    city: "Shelbyville",
    state: "TN",
    zipCode: "37160",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    age: 23,
    street: "789 Pine Road",
    city: "Centerville",
    state: "OH",
    zipCode: "45459",
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob.brown@example.com",
    age: 45,
    street: "101 Elm Street",
    city: "Hill Valley",
    state: "CA",
    zipCode: "95420",
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie.davis@example.com",
    age: 30,
    street: "202 Birch Boulevard",
    city: "Riverdale",
    state: "NY",
    zipCode: "10463",
  },
  {
    id: 6,
    name: "Diana Evans",
    email: "diana.evans@example.com",
    age: 29,
    street: "303 Cedar Lane",
    city: "Gotham",
    state: "NJ",
    zipCode: "07097",
  },
  {
    id: 7,
    name: "Edward Foster",
    email: "edward.foster@example.com",
    age: 38,
    street: "404 Walnut Drive",
    city: "Smallville",
    state: "KS",
    zipCode: "66002",
  },
  {
    id: 8,
    name: "Fiona Green",
    email: "fiona.green@example.com",
    age: 27,
    street: "505 Cherry Street",
    city: "Metropolis",
    state: "NY",
    zipCode: "10001",
  },
  {
    id: 9,
    name: "George Harris",
    email: "george.harris@example.com",
    age: 50,
    street: "606 Aspen Avenue",
    city: "Star City",
    state: "AR",
    zipCode: "71667",
  },
  {
    id: 10,
    name: "Hannah Irwin",
    email: "hannah.irwin@example.com",
    age: 22,
    street: "707 Maple Drive",
    city: "Coast City",
    state: "CA",
    zipCode: "94501",
  },
];
