# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Neuron Packages

on:
  push:
    branches:
      - master
env:
  VERSION: "0.0.0-alpha.${{ github.run_number }}"

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Project Packages
        run: npm install
      - name: Run Vanilla Neuron tests
        run: cd packages/vanilla-neuron && npm install --legacy-peer-deps && npm run tests && cd ../../

  Build:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install Project Packages
        run: npm install
      - name: Build Vanilla Neuron Package
        run: cd packages/vanilla-neuron && npm install --legacy-peer-deps && npm run build && cd ../../

  Publish:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install Project Packages
        run: npm install
      - name: Publish Vanilla Neuron
        run: cd packages/vanilla-neuron && npm install --legacy-peer-deps && npm run build && cd dist && npm version ${{ env.VERSION }} --no-git-tag-version && npm publish --access public && cd ../../
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
